<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-02 20:40
=======
# Generated by Django 5.2.3 on 2025-07-12 15:33
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringFeedback',
<<<<<<< HEAD
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_feedback',
            },
        ),
        migrations.CreateModel(
            name='MentoringSessionEnrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'mentoring_session_enrollments',
            },
        ),
        migrations.CreateModel(
            name='MentoringSessions',
=======
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.JSONField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Mentors',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise_area', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('availability_schedule', models.TextField(blank=True, null=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('rating_average', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_sessions_conducted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentors',
=======
            name='MentoringSessionEnrollments',
            fields=[
                ('session_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_session_enrollments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MentoringSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentors',
                'managed': True,
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d
            },
        ),
    ]
