<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-02 20:40
=======
# Generated by Django 5.2.3 on 2025-07-12 15:33
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('mentoring', '0001_initial'),
        ('students', '0001_initial'),
<<<<<<< HEAD
=======
        ('university_students', '0001_initial'),
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='mentoringsessionenrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='mentoringsessionenrollments',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentoringsessions'),
        ),
        migrations.AddField(
            model_name='mentoringfeedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentoringsessions'),
        ),
        migrations.AddField(
            model_name='mentors',
<<<<<<< HEAD
=======
            name='university_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university_students.universitystudents'),
        ),
        migrations.AddField(
            model_name='mentors',
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users'),
        ),
        migrations.AddField(
            model_name='mentoringsessions',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentors'),
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='mentoringfeedback',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentors'),
        ),
=======
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d
    ]
