<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-02 20:40
=======
# Generated by Django 5.2.3 on 2025-07-12 15:33
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0001_initial'),
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringpayments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutoringsessions'),
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='tutoringpayments',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutors'),
        ),
=======
>>>>>>> c58690afdcbaf86d63e4e395000c9e3f86743a8d
    ]
